### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Myeongwon-Kang** [phajduk/dagger2-example#3]
hi
Lucky that I made an example two dagger.
Dagger2, providing Retrofit instance with diffrent url...
i wanted to use openwhereapi and githubapi together.
i think it is going to do modification debugapimoude, apimodule....
Can i help you

thinks

**Comment by phajduk** [comment]
Thanks for suggestion. I would like to keep this example as simple as possible. I'm not happy with adding any additional API like OpenWeather API.
